# Generated by Django 4.1.1 on 2022-09-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_certificate_alter_about_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
