# Generated by Django 4.1.1 on 2022-09-20 11:56

from django.db import migrations, models
import portfolio.src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('site_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='imgs/project_img', validators=[portfolio.src.validators.MaxFileSizeInMbValidator(5)])),
            ],
        ),
    ]
