# Generated by Django 4.1.1 on 2022-09-21 15:04

import cloudinary.models
from django.db import migrations, models
import portfolio.src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[portfolio.src.validators.MaxFileSizeInMbValidator(5)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, default='imgs/default-cover-bg.png', null=True, upload_to='imgs/project_img', validators=[portfolio.src.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
