# Generated by Django 4.1.1 on 2022-09-22 14:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_project_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
