# Generated by Django 4.1.1 on 2022-09-22 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_project_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dpdcgsg6l/image/upload/v1663857725/default-cover-bg_x7gl5j.png', max_length=255, null=True),
        ),
    ]
